### ISSUE TITLE
just init - error: failed to compile `cargo-udeps v0.1.41`

### ISSUE THREAD

**Issue by x011** [raffomania/aharc#1]
I'm unable to run this project due to an error on `just init`:
```
Compiling cargo v0.72.1
error: could not compile `cargo` (lib)

Caused by:
  process didn't exit successfully: `/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name cargo --edition=2021 /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-0.72.1/src/cargo/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=129 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C metadata=dfeab6db10d997c0 -C extra-filename=-dfeab6db10d997c0 --out-dir /tmp/cargo-installgRKFmE/release/deps -C strip=symbols -L dependency=/tmp/cargo-installgRKFmE/release/deps --extern anyhow=/tmp/cargo-installgRKFmE/release/deps/libanyhow-2056c4f95393e774.rmeta --extern base64=/tmp/cargo-installgRKFmE/release/deps/libbase64-6e993344c7fb3c2e.rmeta --extern bytesize=/tmp/cargo-installgRKFmE/release/deps/libbytesize-b9df4588b8b14535.rmeta --extern cargo_platform=/tmp/cargo-installgRKFmE/release/deps/libcargo_platform-309ce25f90eace2f.rmeta --extern cargo_util=/tmp/cargo-installgRKFmE/release/deps/libcargo_util-7eef08127841f3f4.rmeta --extern clap=/tmp/cargo-installgRKFmE/release/deps/libclap-006201a193f6b03f.rmeta --extern crates_io=/tmp/cargo-installgRKFmE/release/deps/libcrates_io-d241db66d213ce4e.rmeta --extern curl=/tmp/cargo-installgRKFmE/release/deps/libcurl-1e7ef6ecfc93b7e0.rmeta --extern curl_sys=/tmp/cargo-installgRKFmE/release/deps/libcurl_sys-4c24eb29aa172b4d.rmeta --extern env_logger=/tmp/cargo-installgRKFmE/release/deps/libenv_logger-42000e2092e025e4.rmeta --extern filetime=/tmp/cargo-installgRKFmE/release/deps/libfiletime-61804329a9e97702.rmeta --extern flate2=/tmp/cargo-installgRKFmE/release/deps/libflate2-25bca03e9dc0cd6c.rmeta --extern git2=/tmp/cargo-installgRKFmE/release/deps/libgit2-9eaac4095bd48ee3.rmeta --extern git2_curl=/tmp/cargo-installgRKFmE/release/deps/libgit2_curl-02c6a0388e1d2fa1.rmeta --extern gix=/tmp/cargo-installgRKFmE/release/deps/libgix-8da0f8b846907f9a.rmeta --extern gix_features_for_configuration_only=/tmp/cargo-installgRKFmE/release/deps/libgix_features-100b8dcb6040bcd8.rmeta --extern glob=/tmp/cargo-installgRKFmE/release/deps/libglob-dd2514d9866f2576.rmeta --extern hex=/tmp/cargo-installgRKFmE/release/deps/libhex-1539682706018fb0.rmeta --extern hmac=/tmp/cargo-installgRKFmE/release/deps/libhmac-8226a689ee63a3d6.rmeta --extern home=/tmp/cargo-installgRKFmE/release/deps/libhome-2cb1307591cede11.rmeta --extern http_auth=/tmp/cargo-installgRKFmE/release/deps/libhttp_auth-175d46924445f298.rmeta --extern humantime=/tmp/cargo-installgRKFmE/release/deps/libhumantime-6c514dfff03bfe92.rmeta --extern ignore=/tmp/cargo-installgRKFmE/release/deps/libignore-3b8081b2281853b8.rmeta --extern im_rc=/tmp/cargo-installgRKFmE/release/deps/libim_rc-c81beff7cc42984f.rmeta --extern indexmap=/tmp/cargo-installgRKFmE/release/deps/libindexmap-7a94f9c372418038.rmeta --extern is_terminal=/tmp/cargo-installgRKFmE/release/deps/libis_terminal-f540cb965d25c2af.rmeta --extern itertools=/tmp/cargo-installgRKFmE/release/deps/libitertools-6c7e5c3cee6dd23e.rmeta --extern jobserver=/tmp/cargo-installgRKFmE/release/deps/libjobserver-9594232bdcd4bbad.rmeta --extern lazy_static=/tmp/cargo-installgRKFmE/release/deps/liblazy_static-a8ed0d36d7a69372.rmeta --extern lazycell=/tmp/cargo-installgRKFmE/release/deps/liblazycell-2cfb84c64a2aa95e.rmeta --extern libc=/tmp/cargo-installgRKFmE/release/deps/liblibc-30a20c12bf1dbc3a.rmeta --extern libgit2_sys=/tmp/cargo-installgRKFmE/release/deps/liblibgit2_sys-1e5b9056de9a8565.rmeta --extern log=/tmp/cargo-installgRKFmE/release/deps/liblog-6fd0f07a4ce8d66d.rmeta --extern memchr=/tmp/cargo-installgRKFmE/release/deps/libmemchr-81fcabffbfbddc00.rmeta --extern opener=/tmp/cargo-installgRKFmE/release/deps/libopener-77bad5fbf3f2e49c.rmeta --extern os_info=/tmp/cargo-installgRKFmE/release/deps/libos_info-6badf139eae29c7e.rmeta --extern pasetors=/tmp/cargo-installgRKFmE/release/deps/libpasetors-61ae8bc465951be0.rmeta --extern pathdiff=/tmp/cargo-installgRKFmE/release/deps/libpathdiff-1716a3abe30e85b4.rmeta --extern rand=/tmp/cargo-installgRKFmE/release/deps/librand-67dccd08add74458.rmeta --extern rustfix=/tmp/cargo-installgRKFmE/release/deps/librustfix-c6b1e468025d1e4a.rmeta --extern semver=/tmp/cargo-installgRKFmE/release/deps/libsemver-dd6496872344f289.rmeta --extern serde=/tmp/cargo-installgRKFmE/release/deps/libserde-baf407a4de6be2df.rmeta --extern serde_value=/tmp/cargo-installgRKFmE/release/deps/libserde_value-5660db7ad0928eac.rmeta --extern serde_ignored=/tmp/cargo-installgRKFmE/release/deps/libserde_ignored-468f776cb9b54ca0.rmeta --extern serde_json=/tmp/cargo-installgRKFmE/release/deps/libserde_json-7861a60f4d0f2bb3.rmeta --extern sha1=/tmp/cargo-installgRKFmE/release/deps/libsha1-c6fc1905558476e2.rmeta --extern shell_escape=/tmp/cargo-installgRKFmE/release/deps/libshell_escape-b9f70fa7b4ea5199.rmeta --extern strip_ansi_escapes=/tmp/cargo-installgRKFmE/release/deps/libstrip_ansi_escapes-0a81f28495a2615b.rmeta --extern tar=/tmp/cargo-installgRKFmE/release/deps/libtar-ebea5366f05a6cf2.rmeta --extern tempfile=/tmp/cargo-installgRKFmE/release/deps/libtempfile-9f6b3dee7a8bb5a8.rmeta --extern termcolor=/tmp/cargo-installgRKFmE/release/deps/libtermcolor-c80389f643e59105.rmeta --extern time=/tmp/cargo-installgRKFmE/release/deps/libtime-517b20f827cabbcc.rmeta --extern toml=/tmp/cargo-installgRKFmE/release/deps/libtoml-7966a519bf700df6.rmeta --extern toml_edit=/tmp/cargo-installgRKFmE/release/deps/libtoml_edit-c8c07ce0bbc1f572.rmeta --extern unicode_width=/tmp/cargo-installgRKFmE/release/deps/libunicode_width-13f2590755c321ef.rmeta --extern unicode_xid=/tmp/cargo-installgRKFmE/release/deps/libunicode_xid-01ff37d6de449460.rmeta --extern url=/tmp/cargo-installgRKFmE/release/deps/liburl-1a1d8c9ea33ead2e.rmeta --extern walkdir=/tmp/cargo-installgRKFmE/release/deps/libwalkdir-429d66fadf848984.rmeta --cap-lints allow -L native=/tmp/cargo-installgRKFmE/release/build/curl-sys-ccd9b0e75736c967/out/build -L native=/tmp/cargo-installgRKFmE/release/build/libnghttp2-sys-f33a7877b9213910/out/i/lib -L native=/tmp/cargo-installgRKFmE/release/build/libgit2-sys-63cf82edb560503e/out/build -L native=/tmp/cargo-installgRKFmE/release/build/libssh2-sys-58b6daf96b151cac/out/build` (signal: 9, SIGKILL: kill)
error: failed to compile `cargo-udeps v0.1.41`, intermediate artifacts can be found at `/tmp/cargo-installgRKFmE`
error: Recipe `init` failed on line 101 with exit code 101
```
any idea how to solve this?

**Comment by raffomania** [comment]
Hmm, I'm not sure what the cause could be - is your rust toolchain up to date?

**Comment by x011** [comment]
I've tested with a different OS (Ubuntu 20.04, previously Rocky 9) and encountered the same error. This is what I've done:

```
apt update
apt install build-essential
apt install cargo
apt install npm
curl https://sh.rustup.rs -sSf | sh 
export PATH="/root/.cargo/bin:$PATH"
cargo install just
git clone https://github.com/raffomania/archive.observer.git
cd archive.observer
just init
```

I'm not sure if my "_rust toolchain up to date_" because I'm actually new to rust, but I've tried `rustup update`, which  outputs :

```
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: checking for self-update

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.71.0 (8ede3aae2 2023-07-12)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.73.0-nightly (1d56e3a6d 2023-07-22)

info: cleaning up downloads & tmp directories
```

Can you provide any guidance on how to resolve this?

**Comment by raffomania** [comment]
You could try running `cargo install cargo-udeps -j 1` as was suggested in your issue in the cargo-udeps repo.

However, if you just want to run the project, `just init` will install lots of development stuff you don't need. Try:
```
cargo install pagefind
just run
```

And see if that compiles. If it does, you'll need to provide the needed command line flags to point to your subreddit files and configure the tool, and you're good to go :)

**Comment by x011** [comment]
It seems that `apt install pkg-config` and `rustup default nightly` allowed me to compile without errors.

> you'll need to provide the needed command line flags to point to your subreddit files and configure the tool, and you're good to go :)

This means the I've to rename `.env.example` to `.env` and change the content to something like:

```
RUST_LOG=info
SUBMISSIONS=/absolute/path/to/submissions.json
COMMENTS=/absolute/path/to/comments.json
LIMIT_POSTS=2020-01-01
NETLIFY_TOKEN=token for deploying to netlify
```

or is there any other files that I need to edit? Which are the "command line flags" and where should I use them? Which tool do I need to configure?
Sorry for all the questions, but I'd really like to run this project.

**Comment by x011** [comment]
I'm getting the following error after running `just run`:


```
cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/aharc`
  2023-07-23T20:07:58.382434Z  INFO aharc: Found posts: 0
    at src/lib.rs:86
    in aharc::run with config: Config { submissions: "/input/submissions.json", comments: "/input/comments.json", limit_posts: Some(2022-12-31) }

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)
```

Both `/input/submissions.json` and `/input/comments.json` files are present. Could you suggest what might potentially be the issue?

**Comment by x011** [comment]
I think [this line](https://github.com/raffomania/archive.observer/blob/4c6178489d90afe4fdbae3fbbd17ef098904553e/justfile#L115C51-L115C142) is wrong, 

Shouldn't it be 

`--submissions=input/{{input_name}}_submissions.json --comments=input/{{input_name}}_comments.json`

instead of:

`--submissions=input/{{input_name}}_posts.json --comments=input/{{input_name}}_comments.json`

**Comment by x011** [comment]
No matter which command I use, it always outputs  `No such file or directory (os error 2)`, there's something wrong with the code as  it cannot find any submissions (aka posts) and comments, either using relative or absolute paths.

 - `./aharc  --submissions /meus/submissions.json --comments /meus/comments.json`
 - `just run` (tried .env with relative and also absolute paths)
 - `cargo run --release -- --limit-posts=2022-12-31 --submissions=/meus/submissions.json --comments=/meus/comments.json`
 
Not sure what to try more at this point.

**Comment by raffomania** [comment]
Sorry, the instructions are a bit barebones still.

In case you didn't do that yet, you need to download submissions and comments yourself - google "pushshift archives". You'll also need to decompress them if they are in `gz` or `zstd` format.

If you did download them, where did you put the json files? If they are inside the project folder, you can't use absolute paths.

> --submissions=input/{{input_name}}_submissions.json --comments=input/{{input_name}}_comments.json

This line depends on the names you choose for your json files. You can rename them to match the paths given to the application.

> This means the I've to rename .env.example to .env and change the content

You can either make an .env file and specify options there, or you can pass options on the CLI directly to `just run` (or `cargo run`). `just run -- --help` will tell you how to specify  command line options.

**Comment by x011** [comment]
Hi,
I downloaded the pushshift  zst archives from [the-eye.eu](https://the-eye.eu/redarcs/) and after convert them to json using [`preprocess-dump.sh`](https://github.com/raffomania/archive.observer/blob/main/bin/preprocess-dump.sh), placed them inside a folder named `input` on the project's root folder.

Here's my `.env` file contents:

```
RUST_LOG=info
SUBMISSIONS=input/submissions.json
COMMENTS=input/comments.json
LIMIT_POSTS=2022-12-31
NETLIFY_TOKEN=mykey
```
![2023-07-24_19h30_35](https://github.com/raffomania/archive.observer/assets/4313821/93dc0bb2-bc87-4dc9-9a56-6fe99ab82e4e)

![2023-07-24_19h32_30](https://github.com/raffomania/archive.observer/assets/4313821/34235e2a-c787-4a61-86b8-22bf84201a28)

Everything seems in order, but after running:

`just run --release -- --limit-posts=2022-12-31 --submissions=input/submissions.json --comments=input/comments.json`

I get:

```
cargo run --release -- --limit-posts=2022-12-31 --submissions=input/submissions.json --comments=input/comments.json
    Finished release [optimized] target(s) in 0.09s
     Running `target/release/aharc --limit-posts=2022-12-31 --submissions=input/submissions.json --comments=input/comments.json`
  2023-07-24T18:49:15.377485Z  INFO aharc: Found posts: 0
    at src/lib.rs:86
    in aharc::run with config: Config { submissions: "input/submissions.json", comments: "input/comments.json", limit_posts: Some(2022-12-31) }

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', src/main.rs:15:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: Recipe `run` failed on line 6 with exit code 101
```

Do I need to edit the `justrun` file? The not found error isn't very helpful because it doesn't mention which file it cannot find, I assume it's the json's, but they are where I think they should be, which is inside the input folder.
Can you please double-check if the project's `justrun` is correct?

**Comment by x011** [comment]
> Running `target/release/aharc --limit-posts=2022-12-31 --submissions=input/submissions.json --comments=input/comments.json`

on the back trace above, it seems that `aharc` is trying to load the json files from a relative path inside `target/release/input`?  Is this correct? I tried placing the input folder there, but it also didn't work.

**Comment by raffomania** [comment]
Oh wow. I just found a bug when running in a clean repo.

As a quick fix, you can run `mkdir output` in the project root.

I'll push a commit with a proper fix very soon.

Sorry for the inconvenience!

**Comment by raffomania** [comment]
Fixed the panic in 7f48dbd26642aee29a5969336e86c5848477e4dd.

**Comment by x011** [comment]
Hi,
It fixed the panic, tks, but it continues without finding any posts:

```
 2023-07-26T00:48:12.847280Z  INFO aharc: Found posts: 0
    at src/lib.rs:86
    in aharc::run with config: Config { submissions: "input/submissions.json", comments: "input/comments.json", limit_posts: Some(2022-12-31) }
```

Is it possible to change the code to use absolute paths instead of relative ones? It's just a guess, but this may be the problem. I'm sorry for not being of much help, but I'm very new to rust. If it was in Python, I'd definitively help you.

**Comment by raffomania** [comment]
Oh, that’s probably because of the post limit. Try setting it to 2020-01-01 or so. The pushshift archives don’t contain posts after 2022-12-31.On 26. Jul 2023, at 02:52, x011 ***@***.***> wrote:﻿
Hi,
It fixed the panic, tks, but it continues without finding any posts:
 2023-07-26T00:48:12.847280Z  INFO aharc: Found posts: 0
    at src/lib.rs:86
    in aharc::run with config: Config { submissions: "input/submissions.json", comments: "input/comments.json", limit_posts: Some(2022-12-31) }

**Comment by x011** [comment]
That makes sense, I thought `--limit-posts` was the end date and not the start date, it:'s working perfectly now, thank you so much for your help.

**Comment by raffomania** [comment]
Awesome, glad you could get it to work!

Also I’ll rename that parameter to make it less confusing.

**Comment by raffomania** [comment]
Feel free to close [your issue in cargo-udeps](https://github.com/est31/cargo-udeps/issues/183) as well.
