### ISSUE TITLE
Include custom field

### ISSUE THREAD

**Issue by x011** [raffomania/aharc#2]
Hi,
What would be necessary to include another field into the post?
For example, to include the comment/submission "score"? I assume we need to change lib.rs, render.rs and then the post.jinja template, but I'm not sure where to change exactly.
Also, I would need to recompile the `aharc` after the changes, right?
A sample code would be great, but just some starting tips would also be greatly appreciated.

**Comment by raffomania** [comment]
Since you're only beginning to work with rust, I'd recommend you get started by learning a little bit of rust.  [Reading the rust book](https://doc.rust-lang.org/book/) or doing some [rustlings challenges](https://github.com/rust-lang/rustlings/). You can also find more resources on [the rust language website](https://www.rust-lang.org/learn).

**Comment by x011** [comment]
Hi, 
Though I don't currently have enough time to learn Rust, the solution was simpler than expected. 
All I needed to do was modify `lib.rs` and `render.rs`and insert the following lines (marked as `//new line`):

### lib.rs

```
#[derive(Serialize, Deserialize, Debug)]
struct Comment {
    parent_id: String,
    body: String,
    author: String,
    #[serde(with = "chrono::serde::ts_seconds")]
    created_utc: DateTime<Utc>,
    score: i64, // new line
}

impl From<Comment> for render::Comment {
    fn from(comment: Comment) -> Self {
        let body = decode_html_entities(&comment.body).to_string();
        Self {
            body,
            author: comment.author,
            score: comment.score, // new line
        }
    }
}
```
### render.rs

```
pub struct Comment {
    pub body: String,
    pub author: String,
    pub score: i64,  // new line
}
```

The new `{{comment.score}}` variable was then made available to be used in the `post.jinja` template:

```
  {% for comment in post.comments %}
  <details class="pb-2 border-t border-slate relative" open>
    <summary class="pt-4 pb-2 overflow-hidden
        marker:text-gray-400
        before:box-content 
        before:bg-gray-100 before:hover:bg-gray-300 
        before:border-x-8 before:border-white 
        before:absolute
        before:-left-1 before:bottom-4 before:top-12 before:w-px">
      <em><a href="https://old.reddit.com/u/{{comment.author}}">{{
          comment.author }} {{comment.score}}</a></em>
    </summary>
    <div class="prose ml-5 pb-3 break-words">
      {{ comment.body.as_str()|markdown }}
    </div>
  </details>
  {% endfor %}
```

Thank you for your help. I'm looking forward to learning Rust as soon as I have some extra time.

**Comment by raffomania** [comment]
I'm happy you could make it work!
